FROM eclipse-temurin:21-jdk

LABEL "org.opencontainers.image.authors"="Sabith"

COPY target/account-service-0.0.1-SNAPSHOT.jar account-service-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "account-service-0.0.1-SNAPSHOT.jar"]